### ISSUE TITLE
License of this project?

### ISSUE THREAD

**Issue by Poussinou** [choiman1559/ANeko#2]
Hi @choiman1559 

What's the license of this project?

If it's something open-source like the GNU GPL v3 license, we could try to add it to [F-Droid](https://f-droid.org/) after the license has been added, if you're ok.

**Comment by choiman1559** [comment]
I just added a license to the project. (LGPL-2.1) However, since the app is already distributed on the Play Store, I will not upload the app to a third-party market.

However, if you want to distribute it to a third-party market, fork this project and upload it yourself. I won't care what you do.

**Comment by Poussinou** [comment]
[F-Droid](https://f-droid.org/) builds Android apps from source (this repo), sign them and publish them.

Thanks for your answer.

**Comment by mothdotmonster** [comment]
Providing F-Droid builds allows people who don't use Google services to still download your app. If your app doesn't rely on Google services for any core features (which this obviously doesn't) I see no reason not to try.
